from __future__ import annotations

from typing import Any


class _DynamicObject:
    HSet: Any

    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...


class HAction(_DynamicObject):
    def GetDefault(self, action: str, hset: Any) -> bool: ...
    def Execute(self, action: str, hset: Any) -> bool: ...
    def Run(self, action: str) -> bool: ...


class HParameterSet(_DynamicObject):
    pass


class HeadCtrl(_DynamicObject):
    UserDesc: str
    Next: HeadCtrl | None

    def GetSetItem(self, key: str) -> Any: ...


class Hwp(_DynamicObject):
    HAction: HAction
    HParameterSet: HParameterSet
    HeadCtrl: HeadCtrl | None

    def __init__(self, visible: bool = ...) -> None: ...
    def open(self, path: str, *args: Any, **kwargs: Any) -> bool: ...
    def save_as(self, path: str, *args: Any, **kwargs: Any) -> bool: ...
    def quit(self) -> None: ...
    def Run(self, action: str) -> bool: ...
    def RGBColor(self, red: int, green: int, blue: int) -> int: ...
    def PointToHwpUnit(self, point: int | float) -> int: ...


def __getattr__(name: str) -> Any: ...
